# Generated by Django 3.2.7 on 2022-02-12 17:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('product_brand_name', models.CharField(default='Fitness Club', max_length=1000000)),
                ('product_description', models.TextField(blank=True)),
                ('product_aviablity', models.PositiveIntegerField()),
                ('product_rate', models.PositiveIntegerField()),
                ('product_payable_rate', models.PositiveIntegerField(default='1')),
                ('product_image', models.ImageField(blank=True, upload_to='product_Images/')),
                ('product_searchEngine', models.CharField(default='GYM', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(default=0, max_length=10)),
                ('pincode', models.IntegerField(default=0, max_length=6)),
                ('address', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='user_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
